// <auto-generated />
namespace OceanicAirlines.Infrastructue.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dbinitialmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dbinitialmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202110141510141_Db-initial-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
